//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptionProcam.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetDetail
    {
        public tblAssetDetail()
        {
            this.tblAssetIssueDetails = new HashSet<tblAssetIssueDetail>();
        }
    
        public int ID { get; set; }
        public string AssetModelName { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> AssetCompanyID { get; set; }
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsIssued { get; set; }
        public string LicesenceNo { get; set; }
    
        public virtual tblAssetCompany tblAssetCompany { get; set; }
        public virtual tblAssetType tblAssetType { get; set; }
        public virtual ICollection<tblAssetIssueDetail> tblAssetIssueDetails { get; set; }
    }
}
