//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptionProcam.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDetail
    {
        public int ID { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> EmpDesignationID { get; set; }
        public string EmpDept { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblEmpDesignationMaster tblEmpDesignationMaster { get; set; }
    }
}
